package VA::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';
=perl
__PACKAGE__->config(
    schema_class => 'VA::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:vadb',
        user => 'vaadmin',
        password => 'viblio',
        mysql_enable_utf8 => q{1},
        AutoCommit => q{1},
    }
);
=cut
=head1 NAME

VA::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<VA>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<VA::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Andrew Peebles

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
