package VA::Model::RDS;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'VA::RDSSchema',
    traits => ['Caching'],
    connect_info => {
        dsn => 'dbi:mysql:database=video_dev_1;host=testpub.c9azfz8yt9lz.us-west-2.rds.amazonaws.com',
        user => 'web_dev',
        password => 'Yn8U!2Y52Pt#5MEK',
        cursor_class => q{DBIx::Class::Cursor::Cached},
        mysql_enable_utf8 => q{1},
        AutoCommit => q{1},
    }
);

=head1 NAME

VA::Model::RDS - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<VA>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<VA::RDSSchema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.63

=head1 AUTHOR

Viblio

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
